### ISSUE TITLE
Greying out background when opening dropdown button

### ISSUE THREAD

**Issue by Tixierae** [dreamRs/shinyWidgets#223]
When opening a dropdown button, how to grey out the rest of the app? (everything but the content of the expanded button). Just like what is done with the sweet alerts. Thank you for any suggestion.

**Comment by pvictor** [comment]
Hello,
Probably doable in CSS, try this hacky CSS : 

```css
.dropdown.open > .dropdown-menu {
  box-shadow: 0 0 0 1000vh rgba(0, 0, 0, 0.5), 0 5px 5px rgba(0, 0, 0, 0.5);
}
```

Victor
